### ISSUE TITLE
Ask user if he wants to play again, otherwise break

### ISSUE THREAD

**Issue by mayisa87** [laurkp/slotMachine#18]
https://github.com/laurkp/slotMachine/blob/e05b0a4b040e6e7f80a4363a6f923dc44a8dcc72/slotMachine/Program.cs#L24

When does this loop stop, currently the program is executed over and over again. Add an check if user wants to play again at all.

**Comment by incredibleLeitman** [comment]
If you have only one break condition for your loop you should place it in the loop header.
When you are providing multiple break-conditions you can use a while(true) loop but should mention the exit terminations in a comment above the loop.
