### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by incredibleLeitman** [laurkp/slotMachine#22]
You should come up with better names for your function names and variables in your program.
For example "Prompt" is a term that is usually used when printing something to let the user enter a value,
but in your code you use it for just displaying things. All those functions should better be named with something that starts with "Show" or "Display" or something like that.

Overall a good hint for coming up with proper names for functions is to start with a verb.
Instead of "UserStake" you should name that function "ShowUserStake" or something like that (same goes for "Bet", "StakeToPlay" etc...)

Also your variables are not always make sense:
first you start assigning the amount of credits the user wants to bet for this round
```double betAmount = UISlotMethods.Bet(moneyToPlay);``` which is ok 👍 
but then you override this value with the winnings?
```betAmount += Logic.CalcWinnings(winList, loseList, stakeIdx, isWin);```
and print that as "Bet: x" ? 🤔 This is very confusing

Speaking of, a player has no idea where those values are coming from,
I suggest you print a little more introduction text that explains the user how the slotmachine is working an what are the possible winnings and when they are triggered

**Comment by incredibleLeitman** [comment]
This issue is only partially solved ☝️ 

"betAmount" is still used for the bet and the winning which is very confusing

**Comment by incredibleLeitman** [comment]
Or maybe I just get confused by the terminology you are using? I noticed that Isabella also had problems understanding what your variables are meaning 🤔 

bet is usually for what the user spends to get the spin started,
win/prize or something like that is the amount the user gets when hitting matching lines,
and there should be a variable that stores the total remaining credits the user has available for playing which gets deducted the bet and added the wins.
You do all of this things correctly but your variable naming making things harder to follow

**Comment by laurkp** [comment]
I had a separate variable declared but Isabella said I should remove it check on WhatsApp msg this is her comment: do you need really all 3 variables or can you go for 2 or maybe only one?
double newBank = playBank + betAmount;
moneyToPlay = newBank;

**Comment by incredibleLeitman** [comment]
Yes, this is exactly what I am referring to:
As Isabella mentioned you probably dont need 3 variables for tracking the user credtis,
I think you could just modify "moneyToPlay" by substracting the betAmount and adding the winnings.
But you should not use the same variable as a storage for two differrent things like the bet and the wins ☝️
