### ISSUE TITLE
Don't modify your method parameters

### ISSUE THREAD

**Issue by henrikmdev** [laurkp/slotMachine#23]
https://github.com/laurkp/slotMachine/blob/e74193d6f1836f35c32ae6e931de8fa121c74d52/slotMachine/Program.cs#L77
https://github.com/laurkp/slotMachine/blob/e74193d6f1836f35c32ae6e931de8fa121c74d52/slotMachine/UISlotMethods.cs#L146
https://github.com/laurkp/slotMachine/blob/e74193d6f1836f35c32ae6e931de8fa121c74d52/slotMachine/UISlotMethods.cs#L162
https://github.com/laurkp/slotMachine/blob/e74193d6f1836f35c32ae6e931de8fa121c74d52/slotMachine/UISlotMethods.cs#L164

Your arguments should be thought of as inputs to your function. Then, the output of the function is returned. Usually, you should create a separate local variable in your method and then return that variable based on the input parameters.

Okay, now the reason for why your code isn't working the way you think...
When method parameters are passed into the method, the value is passed by default. Not the variable itself. This is called "passing by value". So by the time you are in your method, you don't have access to the variable that was passed anymore. Then, if you try to modify your variable, you are not actually modifying the variable you passed, rather a new variable that has the value of your original variable.

If you want to modify the original variable that you passed to the method, you need to pass not only the value, but a reference to that value. This is called "passing by reference".

**Comment by incredibleLeitman** [comment]
@laurkp You also do this for the "AssignDynamicSlotNumbers" method:
https://github.com/laurkp/slotMachine/blob/fd0815a282fe45c99c688579c7659d044769b2c4/slotMachine/Logic.cs#L38-L47

It would be better to create a new array inside the function and return it, 
than passing the grid as input param and modify it
