### ISSUE TITLE
Remove magic number and correct random.next

### ISSUE THREAD

**Issue by mayisa87** [laurkp/slotMachine#29]
https://github.com/laurkp/slotMachine/blob/1ce833e38a2c5e46e0d754aaf432d2747f70d406/slotMachine/Logic.cs#L44

Please move 10 to an constant, like MAX_NUMBER and for 1 you could define a MIN_NUMBER, and about the random.Next(1, 10); If you hover over the Next method, you will get the information, Next returns a number >= 1 and <10 in your case, so you should always go for:

```random.Next(1, 10**+1**);```

If you want to start at 1 anyway, you can also use the ```random.Next(10+1); ``` so you don't need a MIN_NUMBER constant at all :)

**Comment by laurkp** [comment]
My intention was to get on the grid numbers from 1 to 9 included not 10.

**Comment by mayisa87** [comment]
Ok, then it's of course fine!
